# download previous compare history for this branch
# - continue-on-error whenever this is a first run for the selected branch BECAUSE there is no history file is available to download
# create a current SBOM
# create a previous SBOM from:
#  - pull_request, use base repository
#  - push, use the previous commit
#  - workflow_dispatch, use the previous commit (same as push)
# DIFF the SBOMs and report
# create CSVs for easier human use
# upload artifacts (for sbom-reports.zip, and carryover.zip)

name: SBOM compare
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

permissions:
    actions: read

jobs:
  sbom-compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Fetch all previous commits, changed from 2 (last) to 0 (all)
          ref: ${{ github.head_ref }}
         
      - name: Install Dependencies
        run: |
          # cdxgen (create current AND previous, in CDX format ) 
          npm install -g @cyclonedx/cdxgen

          # cycloneDX (create CSV from either format SBOM)
          # suggested install requires brew (not present) download the asset directly
          wget -O cyclonedx https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.30.0/cyclonedx-linux-x64
          chmod 777 cyclonedx

          # sbomdiff (create a DIFF from either format SBOM into TXT)
          pip install sbomdiff

      - name: setup artifact folder
        run: mkdir .sbom

      - name: Download carryover file from last successful run of this branch
        id: dl-prev-carryover-zip
        # fail expected if no previous github action run exists - allow the script to continue
        continue-on-error: true
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_WITH_CARRYOVER=${{ github.head_ref }}
          else
            BRANCH_WITH_CARRYOVER=${{ github.ref_name }}
          fi
          ARTIFACTS_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/ssc-dsai/canchat-v2/actions/workflows/sbom-compare.yml/runs?status=success&branch=${BRANCH_WITH_CARRYOVER}" \
            | jq -r '.workflow_runs
              | if length > 0 then .[0].artifacts_url else empty end')
          echo "Artifacts URL: ${ARTIFACTS_URL}"
          ARCHIVE_DOWNLOAD_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${ARTIFACTS_URL}?name=carryover.zip" \
            | jq -r '.artifacts
              | if length > 0 then .[0].archive_download_url else empty end')
          echo "Archive download URL: ${ARCHIVE_DOWNLOAD_URL}"
          curl -sS -L -o .sbom/carryover.zip -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" "${ARCHIVE_DOWNLOAD_URL}"
          unzip .sbom/carryover.zip -d .sbom
          ls -R .sbom
          
      - name: Generate Current SBOM CDX format
        id: current-sbom-cdx
        run: |
          cdxgen -o .sbom/current.cdx.json --json-pretty
          echo "current_sbom=.sbom/current.cdx.json" >> $GITHUB_OUTPUT

      - name: Generate Previous SBOM CDX format
        id: previous-sbom-cdx
        run: |
          echo "github.event_name = ${{ github.event_name }}"
          echo "Base and Head variables exist if PR:"
          echo "  - github.base_ref = ${{ github.base_ref }}"
          echo "  - github.head_ref = ${{ github.head_ref }}"
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git checkout ${{ github.base_ref }}
            cdxgen -o .sbom/previous.cdx.json --json-pretty
            git checkout ${{ github.head_ref }}
          else
            git checkout HEAD^
            cdxgen -o .sbom/previous.cdx.json --json-pretty
            git checkout -
          fi
          echo "previous_sbom=.sbom/previous.cdx.json" >> $GITHUB_OUTPUT

      - name: Create CSVs
        id: convert-sboms
        run: ./cyclonedx convert --input-file .sbom/current.cdx.json --output-file .sbom/current.cdx.csv

      - name: Compare CDX SBOMs
        id: compare-sbom-cdx
        continue-on-error: true
        run: sbomdiff .sbom/previous.cdx.json .sbom/current.cdx.json --sbom cyclonedx --format text > .sbom/comparison.cdx.md

      - name: Get PR number
        id: get-pr-number
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_NUMBER=$(jq -r '.number' "$GITHUB_EVENT_PATH")
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "push" ]; then
            echo "pr_number=none (push)" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "pr_number=none (workflow_dispatch)" >> $GITHUB_OUTPUT
          else
            echo "pr_number=none" >> $GITHUB_OUTPUT
          fi
       
      - name: create summary
        id: create-summary
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S %Z")
          echo "# Pull Request Number: ${{ steps.get-pr-number.outputs.pr_number }}"  > .sbom/comparison.md
          echo "## Run Timestamp: $TIMESTAMP" >> .sbom/comparison.md
          
          # CDX version
          echo "" >> .sbom/comparison.md
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "### Comparison to base repository" >> .sbom/comparison.md
          else
            echo "### Comparison to previous commit" >> .sbom/comparison.md
          fi
          cat .sbom/comparison.cdx.md >> .sbom/comparison.md # copy differnces to the historic version

          # prepend current comparison log to the top of the comparison history file (most recent first)
          echo "" >> .sbom/comparison.md
          if test -f .sbom/comparison-history.md; then cp .sbom/comparison-history.md .sbom/old-comparison-history.md; fi
          cp .sbom/comparison.md .sbom/comparison-history.md
          if test -f .sbom/old-comparison-history.md; then 
            cat .sbom/old-comparison-history.md >> .sbom/comparison-history.md
          fi
          cat .sbom/comparison-history.md >> $GITHUB_STEP_SUMMARY

      - name: show artifacts in run log before upload
        run: ls -R .sbom    # gut check

      - name: Upload sbom-reports
        uses: actions/upload-artifact@v7
        with:
          name: sbom-reports.zip
          include-hidden-files: true
          path: |
            .sbom/comparison.md
            .sbom/current.cdx.csv
            .sbom/current.cdx.json

      - name: Upload carryover
        uses: actions/upload-artifact@v7
        with:
          name: carryover.zip
          include-hidden-files: true
          path: |
            .sbom/comparison-history.md
