# target steps:
# download current SBOM (from github - SPDX format)
# download previous SBOM (from previous run artifact)
# - lack of github SBOM sort order detects changes incorectly, solution is to sort
# - occasional workflow failures and artifacts expiring will cause issues with previous artefact availability for a current run
#  - solution: create a 'previous' and 'current' SBOM in the same script (use CDX, newer more robust format)
# DIFF the SPDX files (prev from last action run)
# DIFF the CDX files (prev from last commit)
# create CSVs for easier human usability (sbom-to-excel would be nicer but the conversion tool is not robust and crashing on content)
# upload carryover and other artifacts

name: SBOM compare
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

permissions:
    actions: read

jobs:
  sbom-compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Fetch all previous commits, changed from 2 (last) to 0 (all)
#          ref: ${{ github.head_ref }}
         
      - name: Install Dependencies
        run: |
          # cdxgen (create current AND previous, in CDX format ) 
          npm install -g @cyclonedx/cdxgen

          # cycloneDX (create CSV from either format SBOM)
          # suggested install requires brew (not present) download the asset directly
          wget -O cyclonedx https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.30.0/cyclonedx-linux-x64
          chmod 777 cyclonedx

          # sbomdiff (create a DIFF from either format SBOM into TXT)
          pip install sbomdiff

      - name: setup artifact folder
        run: mkdir .sbom

      - name: Download carryover file from last successful run of this branch
        id: dl-prev-carryover-zip
        # fail expected if no previous github action run exists - allow the script to continue
        continue-on-error: true
        run: |
          echo "token: ${{ secrets.GITHUB_TOKEN }}"
          LAST_WORKFLOW_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/ssc-dsai/canchat-v2/actions/workflows/sbom-compare.yml/runs?status=success&branch=${{ github.ref_name }}" \
            | jq -r '.workflow_runs
              | if length > 0 then .[0].id else empty end')
          echo "Last successful run workflow id: ${LAST_WORKFLOW_ID}"
          LAST_ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/ssc-dsai/canchat-v2/actions/runs/${LAST_WORKFLOW_ID}/artifacts?name=carryover.zip" \
            | jq -r '.artifacts
              | if length > 0 then .[0].id else empty end')
          echo "Last artifact id: ${LAST_ARTIFACT_ID}"
          curl -o .sbom/carryover.zip -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/ssc-dsai/canchat-v2/actions/artifacts/${LAST_ARTIFACT_ID}/zip"

      - name: Generate Current SBOM CDX format
        id: current-sbom-cdx
        run: |
          cdxgen -o .sbom/current.cdx.json --json-pretty
          echo "current_sbom=.sbom/current.cdx.json" >> $GITHUB_OUTPUT

      - name: Generate Previous SBOM CDX format
        id: previous-sbom-cdx
        run: |
          echo "github.event_name = ${{ github.event_name }}"
          if [ "${{ github.event_name }}" == "push" ]; then
            git checkout HEAD^
            cdxgen -o .sbom/previous.cdx.json --json-pretty
            git checkout -
          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            git checkout ${{ github.base_ref }}
            cdxgen -o .sbom/previous.cdx.json --json-pretty
            git checkout ${{ github.head_ref }}
          else
            cp .sbom/current.cdx.json .sbom/previous.cdx.json
          fi
          echo "previous_sbom=.sbom/previous.cdx.json" >> $GITHUB_OUTPUT

      - name: Create CSVs
        id: convert-sboms
        run: ./cyclonedx convert --input-file .sbom/current.cdx.json --output-file .sbom/current.cdx.csv

      - name: Compare CDX SBOMs
        id: compare-sbom-cdx
        continue-on-error: true
        run: sbomdiff .sbom/previous.cdx.json .sbom/current.cdx.json --sbom cyclonedx --format text > .sbom/comparison.cdx.md

      - name: Get PR number
        id: pr
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            # Extract PR number from the event payload
            PR_NUMBER=$(jq -r '.number' "$GITHUB_EVENT_PATH")
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "pr_number=none (push)" >> $GITHUB_OUTPUT
          fi
       
      - name: create summary
        id: create-summary
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S %Z")
          echo "# Pull Request Number: ${{ steps.pr.outputs.pr_number }}"  > .sbom/comparison.md
          echo "## Run Timestamp: $TIMESTAMP" >> .sbom/comparison.md
          
          # CDX version
          echo "" >> .sbom/comparison.md
          echo "### Comparison of current CDX SBOM with previous commit" >> .sbom/comparison.md
          cat .sbom/comparison.cdx.md >> .sbom/comparison.md # copy differnces to the historic version

          # prepend current comparison log to the top of the comparison history file (most recent first)
          echo "" >> .sbom/comparison.md
          cp .sbom/comparison.md .sbom/comparison-history.md
          cat .sbom/comparison-history.md >> $GITHUB_STEP_SUMMARY

      - name: show artifacts in run log before upload
        run: ls -R .sbom    # gut check

      - name: Upload sbom-reports
        uses: actions/upload-artifact@v7
        with:
          name: sbom-reports.zip
          include-hidden-files: true
          path: |
            .sbom/comparison.md
            .sbom/current.cdx.csv
            .sbom/current.cdx.json

      - name: Upload carryover
        uses: actions/upload-artifact@v7
        with:
          name: carryover.zip
          include-hidden-files: true
          path: |
            .sbom/comparison-history.md
